version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${tareas_db}
      MYSQL_USER: ${tarea_user}
      MYSQL_PASSWORD: ${root}
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - /usr/src/app/node_modules

volumes:
  mysql_data:
